### ISSUE TITLE
Nikt nic nie robi 

### ISSUE THREAD

**Issue by michalniebrzydowski** [papryku/mspRefleks#1]
j. w.

**Comment by papryku** [comment]
juz zalatwione szefie ;D

**Comment by michalniebrzydowski** [comment]
Problem wystąpił ponownie

**Comment by papryku** [comment]
panie, ja ciezko pracuje za psie pieniadze i czelnosc masz mi jeszcze wypominac

**Comment by michalniebrzydowski** [comment]
Jaka praca takie pieniądze

**Comment by michalniebrzydowski** [comment]
Pm nie zjawia się w robocie

**Comment by papryku** [comment]
prawda, nic nie robi sie

**Comment by michalniebrzydowski** [comment]
fixed, zamykam
